version: "3.9"

services:
  app_database:
    container_name: app_database
    hostname: app_database
    restart: always
    image: postgres:15.3
    environment:
      POSTGRES_MULTIPLE_DATABASES: test_items_db, items_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_scripts/pg_many_db:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - 1010:5432
    networks:
      - test_db

volumes:
  postgres_data:

networks:
  test_db:
    name: test_db
    driver: bridge
